---
# ver como instala msi em ansible https://github.com/RonaldCarter/PHPmanager/releases/download/V1.5.0/PHPManagerForIIS_V1.5.0.msi
# https://download.microsoft.com/download/1/2/8/128E2E22-C1B9-44A4-BE2A-5859ED1D4592/rewrite_amd64_en-US.msi
# Installing phpmyadmin

- name: Installing packages for php in Windows Server
  win_chocolatey:
    name: '{{ item }}'
    state: latest
  with_items:
    - php
 

- name: Download zip file phpmyadmin
  win_get_url:
    url: https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.zip
    dest: C:\tmp\phpMyAdmin-5.0.2-all-languages.zip

- name: Unzipping phpmyadmin
  win_unzip:
    src: C:\tmp\phpMyAdmin-5.0.2-all-languages.zip
    dest: C:\tmp\phpMyAdmin
    

- name: Move folder phpmyadmin to web folder
  win_copy:
    src: C:\tmp\phpMyAdmin
    dest: C:\Apache\\data\htdocs\phpMyAdmin 
    remote_src: True
  command: mv /tmp/phpMyAdmin-5.0.2-all-languages /usr/share/phpMyAdmin

- name: Copying configuration file
  command: cp -pr /usr/share/phpMyAdmin/config.sample.inc.php /usr/share/phpMyAdmin/config.inc.php

- name: Setting phpmyadmin password
  copy: src={{ item.src}} dest={{item.dest}}
  with_items:
          - { src: 'config.inc.php', dest: '/usr/share/phpMyAdmin/config.inc.php' }

- name: Creating tables phpmyadmin
  mysql_db:
    state: import
    name: phpmyadmin
    login_user: root
    login_password: "{{ mysql_root_password }}"
    target: /usr/share/phpMyAdmin/sql/create_tables.sql

- name: Creating alias for apache web server
  copy: src={{ item.src}} dest={{item.dest}}
  with_items:
           # - { src: 'phpMyAdmin.conf', dest: '/etc/httpd/conf.d/phpMyAdmin.conf' }
             - { src: 'phpMyAdmin.conf', dest: '/etc/apache2/sites-enabled/phpMyAdmin.conf' }

- name: Create diretory tmp
  file:
    path: /usr/share/phpMyAdmin/tmp
    owner: root
    group: root
    mode: '0777'
    state: directory

- name: Restart apache server centos
  systemd:
    name: httpd
    state: reloaded
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: restart apache ubuntu
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Allow phpmyadmin to modify files in /usr/share/phpMyAdmin/
  sefcontext:
    target: '/usr/share/phpMyAdmin/'
    setype: httpd_sys_rw_content_t
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Allow phpmyadmin to modify files in /usr/share/phpMyAdmin/tmp
  sefcontext:
    target: '/usr/share/phpMyAdmin/tmp(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Apply new SELinux file context to filesystem
  command: restorecon -Rv '/usr/share/phpMyAdmin/'
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
     

...
