---

# Installing EPEL Repository

- name: Add the EPEL Repository
  yum:
    name: epel-release
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7","8" or ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7","8")


  # Installing copr plugin

- name: Installing  yum-plugin-copr
  yum:
    name: yum-plugin-copr
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7" or ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")
  
  
# Enable copr repo

- name: Enable copr repo rpmsoftwaremanagement/dnf
  shell: yum copr enable rpmsoftwaremanagement/dnf-nightly -y
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7" or ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

# Removing Yum Utils

- name: Removing yum-utils
  yum:
    name: yum-utils
    state: absent
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7" or ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

# Installing DNF Utils

- name: Installing  dnf
  yum: name={{ dnf_packages }} state=present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7" or ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

...
