---

# Cockpit installation
- name: Cockpit installation
  dnf: name={{ cockpit_packages }} state=latest

# Started Cockpit
- name: Starting cockpit
  systemd:
    name: "cockpit.socket"
    state: "started"
    enabled: true
    daemon_reload: true


...
