---

# Cockpit installation
- name: Cockpit installation
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - cockpit
        - cockpit-machines

# Started Cockpit
- name: Starting cockpit
  systemd:
    name: "cockpit.socket"
    state: "started"
    enabled: true
    daemon_reload: true


...
