---

# Installing the KVM

- name: Installing KVM Packages for CentOS or RedHat 7
  dnf:name={{ kvm_packages_centos7 }} state=latest
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7" or ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

- name: Installing  virt module for CentOS or RedHat 8
  shell: dnf module install virt -y
  when: ansible_virtualization_type == "kvm" and (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8" or ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Installing KVM Packages for CentOS or RedHat 8
  dnf:name={{ kvm_packages_centos8 }} state=latest
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8" or ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Enable and Start libvirtd
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Verify KVM module is loaded
  shell: "lsmod | grep -i kvm"
  register: result
  failed_when: "result.rc != 0"

...
