---

# Installing Apache

- name: Installing Apache Packages for CentOS or RedHat 
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - httpd
        - tar
        - curl

- name: Enable and Start apache service
  systemd:
    name: httpd
    state: started
    enabled: yes

...
