---

# Installing the Wordpress

- name: Creates database for Sinctronics
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Creates database for Sincpress
  mysql_db:
    name: "{{ mysql_dbs }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
 
- name: Create MySQL user for Sinctronics
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for Sincpress
  mysql_user:
    name: "{{ mysql_users }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_dbs }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Download zip file wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz
    mode: '0440'

- name: Unzipping wordpress
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Copying wordpress to sincpress
  command: cp -pr /var/www/html/wordpress /var/www/html/sincpress

- name: Change name wordpress to sinctronics
  command: mv /var/www/html/wordpress /var/www/html/sinctronics

- name: Allow sinctronics to modify files in /var/www/html
  file:
    path: "/var/www/html/sinctronics"
    state: "directory"
    recurse: "yes"
    owner: "root"
    group: "root"
    mode: '0777'
   

- name: Allow sinctronics to modify files in /var/www/html
  file:
    path: "/var/www/html/sincpress"
    state: "directory"
    recurse: "yes"
    owner: "root"
    group: "root"
    mode: '0777'


- name: Allow apache to modify files in /var/www/html
  sefcontext:
    target: '/var/www/html/wordpress'
    setype: httpd_sys_rw_content_t
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv /var/www/html/wordpress
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

...
