---

# Installing ssmtp

- name: Install Compat-openssl
  yum:
    name: https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/compat-openssl10-1.0.2o-3.el8.i686.rpm
    state: present

- name: Install mailx
  yum:
    name: mailx
    state: latest

- name: Install RPM packge ssmtp
  yum:
    name: https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/s/ssmtp-2.64-14.el7.x86_64.rpm
    state: present
  
- name: Copy config files
  copy: src={{ item.src}} dest={{item.dest}}
  with_items:
          - { src: 'ssmtp.conf', dest: '/etc/ssmtp/ssmtp.conf' }
          - { src: 'revaliases', dest: '/etc/ssmtp/revaliases' }

- name: Create simbolic link sendmail
  shell: cp -p /usr/sbin/sendmail /usr/sbin/sendmail.original
  shell: rm /usr/sbin/sendmail
  shell: cd /usr/sbin
  shell: ln -s /usr/sbin/ssmtp sendmail

- name Allowing your server to send emails
  shell: setsebool -P httpd_can_sendmail=on

- name: Send test email
  shell: echo "Isso é um teste de envio de email" | mail -s "Test E-mail" thiago.mliberati@outlook.com
     

...
