---

# Installing ssmtp

- name: Install Compat-openssl
  yum:
    name: https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/compat-openssl10-1.0.2o-3.el8.i686.rpm
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install mailx
  yum:
    name: mailx
    state: latest
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install RPM packge ssmtp
  yum:
    name: https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/s/ssmtp-2.64-14.el7.x86_64.rpm
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install ssmtp Ubuntu
  apt:
    name: ssmtp
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install mail Ubuntu
  apt:
    name: mailutils
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  
- name: Copy config files
  copy: src={{ item.src}} dest={{item.dest}}
  with_items:
          - { src: 'ssmtp.conf', dest: '/etc/ssmtp/ssmtp.conf' }
          - { src: 'revaliases', dest: '/etc/ssmtp/revaliases' }

- name: Delete  symlink existent
  file:
    state: absent
    path: "/usr/sbin/sendmail"
   
- name: Recreate symlink
  file:
    src: "/usr/sbin/ssmtp"
    dest: "/usr/sbin/sendmail"
    state: link

- name: Allowing your server to send emails
  shell: setsebool -P httpd_can_sendmail=on
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

#- name: Send test email
#  shell: echo "Isso é um teste de envio de email" | mail -s "Test E-mail" thiago.mliberati@outlook.com
     

...
