---

# Installing the Mysql

- name: Installing Mysql Packages for CentOS or RedHat
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - mysql-server
        - mysql
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Installing Mysql Packages for Debian or Ubuntu
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
        - python3-mysqldb
        - mysql-server
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Enable and Start mysqld for Centos or RedHat
  systemd:
    name: mysqld
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Start the MySQL service for Debian or Ubuntu
  service: 
    name: mysql 
    state: started
    enabled: true
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install python3-PyMySQL library
  dnf:
    name: python3-PyMySQL
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_pass }}'
    state: present

...
