---

# Installing the Mysql

- name: Installing Mysql Packages for CentOS or RedHat
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - mysql-server
        - mysql

- name: Enable and Start mysqld
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Install python3-PyMySQL library
  dnf:
    name: python3-PyMySQL
    state: present

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_pass }}'
    remove_anonymous_user: true
    disallow_root_login_remotely: true
    remove_test_db: true
    register: mysql_secure
    state: present

...
