---

# Enable firewall rules for Cockpit
- name: Enable firewall rules for Cockpit
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled

# Enable firewall rules for Apache
- name: Enable firewall rules for HTTP
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Enable firewall rules for HTTPS
  firewalld:
    service: https
    permanent: yes
    state: enabled

# Reload firewall
- name: firewalld reload
  command: firewall-cmd --reload


...
