---

# Package management and S.O update
- name: Operating system update
  dnf: name=* state=latest update_cache=yes

- name: Package Installation
  dnf: name={{ common_packages_centos }} state=latest
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

# Timezone configuration
- name: Timezone configuration
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

# copiando arquivo de backup
#- name: copiando arquivo de backup
#  copy: src=backup.tar.xz dest=/tmp/backup.tar.xz

# copy template
- name: Copying a template
  template: src=motd dest=/etc/motd force=yes owner=root group=root


...
