---

# Package management and S.O update

- name: Operating system update
  dnf: name=* state=latest update_cache=yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Debian Like | Update Cache
  apt: update_cache=yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Debian Like | Update System
  apt: name="*" state=latest
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Package Installation for centos
  dnf: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - net-tools
        - vim
        - nmap
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Package Installation for Ubuntu
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - build-essential
        - net-tools
        - bc
        - sudo
        - screen
        - tcpdump
        - telnet
        - nmap
        - vim
        - tree
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

# Timezone configuration
- name: Timezone configuration
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

# copiando arquivo de backup
#- name: copiando arquivo de backup
#  copy: src=backup.tar.xz dest=/tmp/backup.tar.xz

# copy template
- name: Copying a template
  template: src=motd1 dest=/etc/motd force=yes owner=root group=root


...
