---

# Package management and S.O update
- name: Operating system update
  dnf: name=* state=latest update_cache=yes

- name: Package Installation
  dnf: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - net-tools
        - vim
        - nmap

# Timezone configuration
- name: Timezone configuration
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

# copiando arquivo de backup
#- name: copiando arquivo de backup
#  copy: src=backup.tar.xz dest=/tmp/backup.tar.xz

# copy template
- name: Copying a template
  template: src=motd dest=/etc/motd force=yes owner=root group=root


...
