---

# Package management and S.O update
- name: Operating system update
  dnf: name=* state=latest update_cache=yes

- name: Package Installation
  dnf: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - net-tools
        - vim
        - nmap

# Timezone configuration
- name: Timezone configuration
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

# copiando arquivo de backup
#- name: copiando arquivo de backup
#  copy: src=backup.tar.xz dest=/tmp/backup.tar.xz

# copy template
- name: Copying a template
  template: src=motd dest=/etc/motd force=yes owner=root group=root

# Cockpit installation
- name: Cockpit installation
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - cockpit
        - cockpit-machines
          
# Started Cockpit
- name: Starting cockpit
  systemd:
    name: "cockpit.socket"
    state: "started"
    enabled: true
    daemon_reload: true

# Enable firewall rules
#- name: Enable firewall rules
#  firewalld:
#    service: cockpit      
#    permanent: yes
#    state: enabled

# Reload firewall
#- name: firewalld reload
#  command: firewall-cmd --reload

#  yum: name=nginx state=latest
#  notify: restart nginx
...
