---

# Installing phpmyadmin

- name: Installing packages for phpmyadmin in Centos or Redhat 
  dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - wget 
        - php 
        - php-pdo 
        - php-pecl-zip 
        - php-json 
        - php-common 
        - php-fpm 
        - php-mbstring 
        - php-cli
        - php-mysqlnd
        - php-gd
        - php-pdo
        - php-xml
        - policycoreutils-python-utils
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Installing packages for phpmyadmin in Debian 10 or Ubuntu 20
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
        - wget
        - php7.4
        - php7.4-mysql
        - php7.4-common
        - php7.4-mysql
        - php7.4-tidy
        - php7.4-xml
        - php7.4-xmlrpc
        - php7.4-mbstring
        - php7.4-memcached
        - php7.4-curl
        - php7.4-zip
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")

- name: Installing packages for phpmyadmin in Debian 8 or Ubuntu 18
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
        - wget
        - php7.2
        - php7.2-mysql
        - php7.2-common
        - php7.2-mysql
        - php7.2-tidy
        - php7.2-xml
        - php7.2-xmlrpc
        - php7.2-mbstring
        - php7.2-memcached
        - php7.2-curl
        - php7.2-zip
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18")

- name: Download zip file phpmyadmin
  get_url:
    url: https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.tar.gz
    dest: /tmp/phpMyAdmin-5.0.2-all-languages.tar.gz
    mode: '0440'

- name: Unzipping phpmyadmin
  unarchive:
    src: /tmp/phpMyAdmin-5.0.2-all-languages.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move folder phpmyadmin to web folder
  command: mv /tmp/phpMyAdmin-5.0.2-all-languages /usr/share/phpMyAdmin

- name: Copying configuration file
  command: cp -pr /usr/share/phpMyAdmin/config.sample.inc.php /usr/share/phpMyAdmin/config.inc.php

- name: Setting phpmyadmin password
  copy: src={{ item.src}} dest={{item.dest}}
  with_items:
          - { src: 'config.inc.php', dest: '/usr/share/phpMyAdmin/config.inc.php' }

- name: Creating tables phpmyadmin
  mysql_db:
    state: import
    name: phpmyadmin
    login_user: root
    login_password: "{{ mysql_root_password }}"
    target: /usr/share/phpMyAdmin/sql/create_tables.sql

- name: Creating alias for apache web server
  copy: src={{ item.src}} dest={{item.dest}}
  with_items:
           # - { src: 'phpMyAdmin.conf', dest: '/etc/httpd/conf.d/phpMyAdmin.conf' }
             - { src: 'phpMyAdmin.conf', dest: '/etc/apache2/sites-enabled/phpMyAdmin.conf' }

- name: Create diretory tmp
  file:
    path: /usr/share/phpMyAdmin/tmp
    owner: root
    group: root
    mode: '0777'
    state: directory

- name: Restart apache server centos
  systemd:
    name: httpd
    state: reloaded
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: restart apache ubuntu
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Allow phpmyadmin to modify files in /usr/share/phpMyAdmin/
  sefcontext:
    target: '/usr/share/phpMyAdmin/'
    setype: httpd_sys_rw_content_t
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Allow phpmyadmin to modify files in /usr/share/phpMyAdmin/tmp
  sefcontext:
    target: '/usr/share/phpMyAdmin/tmp(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Apply new SELinux file context to filesystem
  command: restorecon -Rv '/usr/share/phpMyAdmin/'
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
     

...
