---

# Installing the Mysql

- name: Download zip file Mysql
  win_get_url:
    url: https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.21-winx64.zip
    dest: C:\tmp\mysql-8.0.21-winx64.zip

- name: Unzipping Mysql
  win_unzip:
    src: C:\tmp\mysql-8.0.21-winx64.zip
    dest: C:\tools\

- name: Create MySQL service
  ansible.windows.win_service:
    name: MySQL
    path: C:\tools\mysql-8.0.21-winx64\mysql-8.0.21-winx64\bin\mysqld.exe


#https://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-community-8.0.21.0.msi

#- name: Installing Mysql Server for Windows


#- name: Set MySQL root Password
#  community.mysql.mysql_user:
#    login_host: 'localhost'
#    login_user: 'root'
#    login_password: ''
#    name: 'root'
#    password: '{{ mysql_pass }}'
#    state: present


...
