---

# Installing the Mysql

- name: Download Mysql Server
  win_get_url:
    url: https://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-community-8.0.21.0.msi
    dest: C:\tmp\mysql-installer-community-8.0.21.0.msi

- name: Install MySql Server
  ansible.windows.win_package:
    path: C:\tmp\mysql-installer-community-8.0.21.0.msi
    arguments:
    - /install
    - /passive
    - /norestart
    state: present
#https://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-community-8.0.21.0.msi

#- name: Installing Mysql Server for Windows


#- name: Set MySQL root Password
#  community.mysql.mysql_user:
#    login_host: 'localhost'
#    login_user: 'root'
#    login_password: ''
#    name: 'root'
#    password: '{{ mysql_pass }}'
#    state: present


...
